const
    REDIS_OPTIONS = {
        host: "127.0.0.1",
        port: 6379
    },
    DEFAULT_WORKERS_AMOUNT = 4,
    MESSAGE_DELAY = 500,
    CAPTURE_GENERATOR_DELAY = 1,
    MESSAGE_WAIT_FOR = CAPTURE_GENERATOR_DELAY,
    MESSAGE_POOL = 1,
    MAX_LIFETIME = 10000,
    ERROR_PERCENT = 0.05;

export {
    REDIS_OPTIONS,
    DEFAULT_WORKERS_AMOUNT,
    MESSAGE_DELAY,
    CAPTURE_GENERATOR_DELAY,
    MESSAGE_WAIT_FOR,
    MESSAGE_POOL,
    MAX_LIFETIME,
    ERROR_PERCENT
}
